// <auto-generated />
using EscombrosDaGuerra.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscombrosDaGuerra.Migrations
{
    [DbContext(typeof(EGContext))]
    partial class EGContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EscombrosDaGuerra.Models.Spells", b =>
                {
                    b.Property<int>("SpellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<short>("SpellComponentMaterial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellComponentMaterialDesc")
                        .HasColumnType("TEXT");

                    b.Property<short>("SpellComponentSomatic")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SpellComponentVerbal")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SpellConcentration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpellConjurationTime")
                        .HasColumnType("INTEGER");

                    b.Property<short>("SpellConjurationTimer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellDuration")
                        .HasColumnType("TEXT");

                    b.Property<int>("SpellLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpellRange")
                        .HasColumnType("TEXT");

                    b.Property<short>("SpellRitual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpellSchool")
                        .HasColumnType("TEXT");

                    b.HasKey("SpellId");

                    b.ToTable("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
